name: Build

on:
  - push

jobs:

  build:
    runs-on:
        - ubuntu-latest
        - windows-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.1

      - name: Build Project
        uses: threeal/cmake-action@v2.0.0

      - name: Test Project
        uses: threeal/ctest-action@v1.1.0
